server:
  undertow:
    # HTTP post内容的最大大小。当值为-1时，默认值为大小是无限的
    max-http-post-size: -1
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 512
    # 是否分配的直接内存
    direct-buffers: true
    threads:
      # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
      io: 8
      # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载，默认值是 io-threads*8
      worker: 256
spring:
  datasource:
    #url: jdbc:mysql://dev.jmlide.com:35458/mall?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=GMT%2B8
    url: jdbc:postgresql://dev.jmlide.com:15432/mall
    username: jmlide
    password: "!Jmlide369258147"
    druid:
      max-active: 3
      remove-abandoned: false
      remove-abandoned-timeout: 1800
  data:
    redis:
      host: dev.jmlide.com
      password: jmlide@redis963
      port: 16379
jetcache:
  remote:
    default:
      uri: redis://jmlide%40redis963@dev.jmlide.com:16379/1?timeout=5s