spring:
  output:
    ansi:
      enabled: always
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,
#      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  redis:
    database: 0
    host: dev.jmlide.com
    password: jmlide@redis963
    port: 16379
    timeout: 100ms

