spring:
  datasource:
    #url: jdbc:mysql://dev.jmlide.com:35458/mall?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=GMT%2B8
    url: jdbc:opengauss://dev.jmlide.com:15432/mall
    username: jmlide
    password: w4Qa1sKe?gr6ye
  redis:
    database: 0
    host: dev.jmlide.com
    password: jmlide@redis963
    port: 16379
jetcache:
  remote:
    default:
      uri: redis://dev.jmlide.com:16379/