spring:
  datasource:
    #url: jdbc:mysql://dev.jmlide.com:35458/mall?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=GMT%2B8
    url: jdbc:postgresql://dev.jmlide.com:15432/mall
    username: jmlide
    password: "!Jmlide369258147"
    druid:
      max-active: 3
  redis:
    host: dev.jmlide.com
    password: jmlide@redis963
    port: 16379
jetcache:
  remote:
    default:
      uri: redis://jmlide%40redis963@dev.jmlide.com:16379/1?timeout=5s