spring:
  output:
    ansi:
      enabled: always
  application:
    name: mall-admin
  profiles:
    active: dev #默认为开发环境
  messages:
    encoding: utf-8
    basename: i18n.messages
    cache-duration: 1
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      enabled: true #默认支持文件上传.
      max-file-size: 100MB #最大支持文件大小
      max-request-size: 100MB #最大支持请求大小
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    redis:
      timeout: 100ms
      database: 14
      lettuce:
        pool:
          max-active: 200  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1     # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10     # 连接池中的最大空闲连接
          min-idle: 0      # 连接池中的最小空闲连接
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.postgresql.Driver
#自动往数据库建表
#    schema:
#      - classpath:department.sql
    druid:
      initial-size: 1
      min-idle: 1
      max-wait: 600000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall,slf4j
      time-between-log-stats-millis: 300000
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      stat-view-servlet:
        enabled: false
        login-password: "mall@963"
        login-username: mall
  main:
    lazy-initialization: true #延迟初始化
  jmx:
    enabled: false #关闭JMX

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: jackson
      limit: 100
  remote:
    default:
      type: redis.lettuce
      keyConvertor: jackson
      broadcastChannel: mall

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: 9f$amuLu3JhU&3DVlx$t3mhsClBIVTiY #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头
  issuer: 'mall'
  leeway: 180
  publicKey: '04DE7FA028257C740D07CCD2682A7A340772E0EED35BB28666E4F916FB26E85D2B5DF709218C84FEE09763753B887C9ECE04414308D241D51BC5F1D93AD3F59CB5'
  privateKey: '93EFFB62F68DB2F28E8FA01E80E6D199EEA1C14DB33C3A86C7A5CD7F3B547ECB'

secure:
  ignored:
    urls: #安全路径白名单
      - /doc.html
      - /swagger-ui.html
      - /swagger-ui/
      - /swagger-resources/**
      - /api-docs
      - /v3/api-docs
      - /v3/api-docs/**
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.map
      - /favicon.ico
      - /actuator/**
      - /druid/**
      - /api/v1/admin/index
      - /api/v1/admin/account/login
      - /api/v1/admin/account/register
      - /api/v1/admin/account/info
      - /api/v1/admin/account/logout
      - /minio/upload
      - /error
      - /api/v1/admin/account/captchaImage
mybatis-plus:
  global-config:
    # 机器id(额外扩展属性)
    worker-id: 2
    # 数据标识id(机房id)
    datacenter-id: 1
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      
management:
  endpoints:
    web:
      exposure:
        include: "*"

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.lam.mall
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  # 开启生产环境屏蔽
  production: true
  setting:
    language: zh_cn

