spring:
  output:
    ansi:
      enabled: always
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 100ms
    jedis:
      pool:
        max-active: 10
        max-idle: 6
        min-idle: 2

